// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Amount = 999.99m,
                            CreatedAtUtc = new DateTime(2026, 2, 26, 12, 26, 2, 452, DateTimeKind.Utc).AddTicks(5967),
                            Currency = "USD",
                            Method = "Card",
                            OrderId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            TransactionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Amount = 599.98m,
                            CreatedAtUtc = new DateTime(2026, 3, 1, 12, 26, 2, 452, DateTimeKind.Utc).AddTicks(6349),
                            Currency = "USD",
                            Method = "BankTransfer",
                            OrderId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            TransactionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Amount = 239.97m,
                            CreatedAtUtc = new DateTime(2026, 3, 3, 12, 26, 2, 452, DateTimeKind.Utc).AddTicks(6357),
                            Currency = "USD",
                            Method = "Card",
                            OrderId = 3,
                            Status = "Processing"
                        },
                        new
                        {
                            TransactionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Amount = 149.95m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 26, 2, 452, DateTimeKind.Utc).AddTicks(6360),
                            Currency = "USD",
                            Method = "Wallet",
                            OrderId = 4,
                            Status = "Completed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
