// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260303122503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName");

                    b.HasIndex("Status");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 2, 26, 12, 25, 1, 899, DateTimeKind.Utc).AddTicks(6884),
                            CustomerName = "John Smith",
                            ProductName = "Laptop",
                            Quantity = 1,
                            Status = "Completed",
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 1, 12, 25, 1, 899, DateTimeKind.Utc).AddTicks(7616),
                            CustomerName = "Jane Doe",
                            ProductName = "Monitor",
                            Quantity = 2,
                            Status = "Processing",
                            UnitPrice = 299.99m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 3, 3, 12, 25, 1, 899, DateTimeKind.Utc).AddTicks(7629),
                            CustomerName = "Bob Johnson",
                            ProductName = "Keyboard",
                            Quantity = 3,
                            Status = "Created",
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 25, 1, 899, DateTimeKind.Utc).AddTicks(7632),
                            CustomerName = "Alice Brown",
                            ProductName = "Mouse",
                            Quantity = 5,
                            Status = "Completed",
                            UnitPrice = 29.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
